export {default as Navbar} from './Navbar/NavBar'
export {default as HeroSection} from './Hero/Hero'
export {default as About} from './About/About'
export {default as Support} from './Support/Support'
export {default as AllInOne} from './AllInOne/AllInOne'